# set the directories below and copy this file as `config.yaml`
data_dir: "./data/"
paper_dir: "./paper/current/"


ribosomal_genes:
  L2: "ribosomal protein L2"
  L3: "ribosomal protein L3"
  L4: "ribosomal protein L4"
  L5: "ribosomal protein L5"
  L14: "ribosomal protein L14"
  L16: "ribosomal protein L16"
  L18: "ribosomal protein L18"
  L22: "ribosomal protein L22"
  L24: "ribosomal protein L24"
  S3: "ribosomal protein S3"
  S8: "ribosomal protein S8"
  S10: "ribosomal protein S10"
  S17: "ribosomal protein S17"
  S18: "ribosomal protein L18"
